myapp/urls.py
app_name = 'myapp'
from .import views
from django.urls import path

urlpatterns = [
    path('',views.index,name = 'index'),
    path('<int:person_id>/',views.detail,name='detail'),
    path('add',views.create_item,name="create_item"),
    path('delete/<int:id>/',views.delete_item,name= 'delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]

myapp/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    def __str__(self):
        return self.first_name
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    contact = models.CharField(max_length=10)
    email = models.CharField(max_length=100)
    user_name = models.CharField(max_length=100)
    image = models.CharField(max_length=500,default="https://cdn.patch.com/assets/contrib/images/placeholder-user-photo.png")

users/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms
from .models import Person

class ItemForm(forms.ModelForm):
    class Meta:
        model=Person							
        fields = ['first_name','last_name','contact','email','user_name','image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Person
from django.template import loader
from .forms import ItemForm

# Create your views here.
def index(request):
    person_list = Person.objects.all()
    context ={
        'person_list':person_list,
    }
    return render(request,'myapp/index.html',context)

def detail(request,person_id):
    item = Person.objects.get(pk = person_id)
    context ={
        'item':item,
    }
    return render(request,'myapp/detail.html',context)

def create_item (request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('myapp:index')

    return render(request,'myapp/item_form.html',{'form':form})

def delete_item(request,id):
    item = Person.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect('myapp/index')
    return render(request,'myapp/item-delete.html',{item:'item'})

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username},you are currently loggedin.')
            return redirect('login')																																					
    else:
        form = RegisterForm()
    return render (request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <div>
                <img src="https://scontent.fblr4-2.fna.fbcdn.net/v/t1.0-1/46341039_2346145605618284_7223169508993662976_n.jpg?_nc_cat=100&_nc_sid=dbb9e7&_nc_ohc=K_HDHuN_qswAX822aJj&_nc_ht=scontent.fblr4-2.fna&oh=59cb6fafcf5580b1c007b71086acde58&oe=5F67B102" height="50px" width="50px" alt="Logo">
                <a href="#" class="navbar-brand"><b>yotaBooks</b></a>
            </div>
            

            <div class="navbar">
                <a class="nav-item nav-link" href="{% url 'myapp:create_item' %}">Add User</a>
                {% if user.is_authenticated %}
                    <div>
                        <a href="{% url 'logout' %}">Logout</a>
                        
                        <a href="{% url 'profile' %}">Profile</a>
                    </div>
                    
                {% else %}
                    <a href="{% url 'login' %}">Login</a>
                {% endif %}

            </div>

        </nav>

        {% if messages %}
            {% for message in messages %}
                <div class='alert alert-{{ message.tags }}'>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}


        {% block body %}
        {% endblock %}
    </body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img height="300px" width="400px" src="{{ item.image }}" class="card"/>
            </div>

            <div class="col-md-6">
                <h1>{{ item.first_name }} {{ item.last_name }}</h1>
                <h3>Mob: {{ item.contact }}</h3>
                <h3>Email: {{ item.email }}</h3>
                <h2>{{ item.user_name }}</h2>
                <a href="{% url 'myapp:delete_item' item.id %}" class="btn btn-primary">Delete</a>
            </div>
        </div>
        
    </div>

    

{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        

    </head>
    <body>
        {% block body %}
            {% for person in person_list %}
            <div class="row">
                <div class="col-md-3 offset-md-2">
                    <img class="card" height="200px" width="200px" src="{{ person.image }}"/>
                </div>
                <div class="col-md-4">
                    <h1>{{ person.first_name }}</h1>
                </div>
                <div class="col-md-2 mt-2">
			        <a href="{% url 'myapp:detail' person.id %}" class ="btn btn-primary">Detail</a>
                </div> 
            </div>

            {% endfor %}   
        {% endblock %}

        {% for person in person_list %}
                <ul>
                    <li>
                        <a href="{% url 'myapp:detail' person.id %}">{{person_id}} - {{ person.first_name }}</a>
                        
                    </li>
                </ul>
        {% endfor %}
    </body>
</html>

myapp/templates/myapp/item-delete.html
<form>
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }} </h2>
    <button type="s">Confirm</button>
</form>

myapp/templates/myapp/item_form.html
{% extends 'myapp/base.html' %}
 
{% block body %}

<div class="container">
   <div class="row">
       <div class="col-md-4 offset-md-4">
           <div class="card">
               <div class="card-header text-white bg-info">
                   <div class="card-title">
                       Add Item
                   </div>
               </div>
               <div class="card-body" style="width: 15rem;">
                   <form method="POST">
                       {% csrf_token %}
                       {{ form }}
                       <button class="btn-info mt-2" type="submit">Sign Up</button>
                   </form>
               </div>
           </div>

       </div>

   </div>

</div>

{% endblock %}

users/templates/users/login.html
{% extends 'myapp/base.html' %}

{% block body %}
 
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}


<!-- <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form> -->

users/templates/users/logout.html
<div>
    <img src="https://cdn.designbyhumans.com/product_images/p/794756.f56.370a3S7ay1Cm2MjUAAA-1200x650-b-p.jpg" height="500px" width="100%" alt="Loggedout">
    <h1 style="text-align: center;">You have been logged out successfully</h1>
</div>

users/templates/users/profile.html
<div>
    <h1>User Name: {{ user.username }}</h1>
</div>

users/templates/users/register.html
{% extends 'myapp/base.html' %}
 
 {% block body %}

 <div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                            </div>
                        {% endfor%}
                        <button class="btn-info" type="submit">Sign Up</button>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

 {% endblock %}


<!-- <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Sign Up</button>
</form> -->